---
abstract: 'Catalyst based application'
author:
  - haw,,,
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Blog
no_index:
  directory:
    - inc
    - t
requires:
  Authentication: 0
  Catalyst::Action::RenderView: 0
  Catalyst::DBD::DBIC: 0
  Catalyst::Model::DBIC: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: '5.90090'
  Catalyst::View::TT: 0
  Config::General: 0
  Moose: 0
  Session: 0
  Session::State::Cookie: 0
  Session::Store::File: 0
  catalyst::Plugin::StackTrace: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: '0.01'
